telemetry:
  interfaces:
    - eth0
    - wlan0
  protocols:
    http: true
    dns: true
    icmp: false

logging:
  level: info
  path: /var/log/dds-agent.log

backend:
  listen_host: localhost
  listen_port: 8080
  forward_host: localhost
  forward_port: 8081
  tls: false


